-- Shipping Zones
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE1', 'China Mainland') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE1', 'Korea, South') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE1', 'Macau SAR') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE1', 'Taiwan') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE10', 'China South') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE10', 'Hong Kong') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE2', 'Indonesia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE2', 'Malaysia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE2', 'Singapore') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE2', 'Thailand') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE2', 'Vietnam') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE3', 'Brunei') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE3', 'Cambodia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE3', 'Laos') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE3', 'Maldives') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE3', 'Myanmar') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE4', 'Australia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE4', 'Guam') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE4', 'India') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE4', 'New Zealand') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE5', 'Canada') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE5', 'Mexico') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE5', 'Puerto Rico') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE5', 'United States') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE6', 'France') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE6', 'Germany') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE6', 'Italy') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE6', 'Netherlands') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE6', 'Spain') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE6', 'United Kingdom') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE7', 'Austria') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE7', 'Denmark') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE7', 'Greece') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE7', 'Portugal') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE7', 'Sweden') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE7', 'Switzerland') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE8', 'Argentina') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE8', 'Egypt') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE8', 'Pakistan') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE8', 'Saudi Arabia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE8', 'Turkey') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE8', 'UAE') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE9', 'Brazil') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE9', 'Jordan') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE9', 'Kenya') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE9', 'South Africa') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Expedited', 'ZONE9', 'Zimbabwe') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE1', 'China Mainland') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE1', 'Korea, South') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE1', 'Macau SAR') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE1', 'Taiwan') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE10', 'China South') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE10', 'Hong Kong') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE2', 'Indonesia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE2', 'Malaysia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE2', 'Singapore') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE2', 'Thailand') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE2', 'Vietnam') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE3', 'Brunei') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE3', 'Cambodia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE3', 'Laos') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE3', 'Maldives') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE3', 'Myanmar') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE4', 'Australia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE4', 'Guam') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE4', 'India') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE4', 'New Zealand') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE5', 'Canada') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE5', 'Mexico') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE5', 'Puerto Rico') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE5', 'United States') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE6', 'France') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE6', 'Germany') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE6', 'Italy') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE6', 'Netherlands') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE6', 'Spain') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE6', 'United Kingdom') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE7', 'Austria') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE7', 'Denmark') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE7', 'Greece') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE7', 'Portugal') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE7', 'Sweden') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE7', 'Switzerland') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE8', 'Argentina') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE8', 'Egypt') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE8', 'Pakistan') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE8', 'Saudi Arabia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE8', 'Turkey') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE8', 'UAE') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE9', 'Brazil') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE9', 'Jordan') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE9', 'Kenya') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE9', 'South Africa') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('UPS', 'Saver', 'ZONE9', 'Zimbabwe') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'A', 'Macau') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'D', 'New Zealand') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'E', 'U.S. (West Region)') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'F', 'Canada') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'F', 'Mexico') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'F', 'U.S.A(Rest of country)') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'G', 'Argentina') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'G', 'Brazil') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'G', 'Costa Rica') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'H', 'Israel') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'H', 'Other Europe') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'H', 'Switzerland') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'I', 'Russia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'I', 'Turkey') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'I', 'United Arab Emirates') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'J', 'Jordan') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'J', 'Saudi Arabia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'J', 'South Africa') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'K', 'China (South)') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'M', 'France') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'M', 'Germany') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'M', 'Italy') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'M', 'United Kingdom') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'N', 'Vietnam') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'O', 'India') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'Q', 'Malaysia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'R', 'Thailand') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'S', 'Philippines') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'T', 'Indonesia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'U', 'Australia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Economy', 'V', 'Hong Kong') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'A', 'Macau') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'D', 'New Zealand') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'E', 'U.S. (West Region)') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'F', 'Canada') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'F', 'Mexico') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'F', 'U.S.A(Rest of country)') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'G', 'Argentina') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'G', 'Brazil') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'G', 'Costa Rica') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'H', 'Israel') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'H', 'Other Europe') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'H', 'Switzerland') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'I', 'Russia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'I', 'Turkey') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'I', 'United Arab Emirates') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'J', 'Jordan') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'J', 'Saudi Arabia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'J', 'South Africa') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'K', 'China (South)') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'M', 'France') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'M', 'Germany') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'M', 'Italy') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'M', 'United Kingdom') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'N', 'Vietnam') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'O', 'India') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'Q', 'Malaysia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'R', 'Thailand') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'S', 'Philippines') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'T', 'Indonesia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'U', 'Australia') ON CONFLICT DO NOTHING;
INSERT INTO shipping_zones (carrier, service, zone_code, country) VALUES ('FedEx', 'Priority', 'V', 'Hong Kong') ON CONFLICT DO NOTHING;