export { Layout } from './Layout';
export type { Page } from './Layout';
export { LeadPage } from './LeadPage';
export { DealPage } from './DealPage';
export { DealCard } from './DealCard';
export { DealForm } from './DealForm';
export { DealDetail } from './DealDetail';
export { KanbanCol } from './KanbanCol';
export { ShipBadge, IncoBadge, PayBadge } from './Badges';
export { Dashboard } from './Dashboard';
export { AccountPage } from './AccountPage';
export { AccountForm } from './AccountForm';
export { AccountDetail } from './AccountDetail';
export { ContactPage } from './ContactPage';
export { ContactForm } from './ContactForm';
export { ContactDetail } from './ContactDetail';
